name = "Fortran-Design-Patterns"

[library]
source-dir = "src"

[build]
auto-tests = false

[[test]]
name = "CoR"
source-dir = "src/behavioral/chain-of-responsibility"
main = "CoR_main.f90"

[[test]]
name = "command"
source-dir = "src/behavioral/command"
main = "command_main.f90"

[[test]]
name = "iterator"
source-dir = "src/behavioral/iterator"
main = "iterator_main.f90"

[[test]]
name = "observer"
source-dir = "src/behavioral/observer"
main = "observer_main.f90"

[[test]]
name = "template_method"
source-dir = "src/behavioral/template-method"
main = "template_method_main.f90"

[[test]]
name = "visitor"
source-dir = "src/behavioral/visitor"
main = "visitor_main.f90"

# - - - - - - - - - -

[[test]]
name = "abstract_factory"
source-dir = "src/creational/abstract-factory"
main = "abstract_factory_main.f90"

[[test]]
name = "builder"
source-dir = "src/creational/builder"
main = "builder_main.f90"

[[test]]
name = "factory"
source-dir = "src/creational/factory"
main = "factory_main.f90"

[[test]]
name = "prototype"
source-dir = "src/creational/prototype"
main = "prototype_main.f90"

[[test]]
name = "singleton"
source-dir = "src/creational/singleton"
main = "singleton_main.f90"

# - - - - - - - - - -

[[test]]
name = "adapter"
source-dir = "src/structural/adapter"
main = "adapter_main.f90"

[[test]]
name = "bridge"
source-dir = "src/structural/bridge"
main = "bridge_main.f90"

[[test]]
name = "composite"
source-dir = "src/structural/composite"
main = "composite_main.f90"

[[test]]
name = "facade"
source-dir = "src/structural/facade"
main = "facade_main.f90"

[[test]]
name = "proxy"
source-dir = "src/structural/proxy"
main = "proxy_main.f90"

[[test]]
name = "wrapper"
source-dir = "src/structural/wrapper"
main = "wrapper_main.f90"