name = "Fortran-Design-Patterns"

[library]
source-dir = "src"

[build]
auto-tests = false

[[test]]
name = "CoR"
source-dir = "src/behavioral/chain-of-responsibility"
main = "CoR_main.f90"

[[test]]
name = "command"
source-dir = "src/behavioral/command"
main = "command_main.f90"

[[test]]
name = "iterator"
source-dir = "src/behavioral/iterator"
main = "iterator_main.f90"

[[test]]
name = "observer"
source-dir = "src/behavioral/observer"
main = "observer_main.f90"

[[test]]
name = "template_method"
source-dir = "src/behavioral/template-method"
main = "template_method_main.f90"

[[test]]
name = "visitor"
source-dir = "src/behavioral/visitor"
main = "visitor_main.f90"

[[test]]
name = "abstract_factory"
source-dir = "src/creational/abstract-factory"
main = "abstract_factory_main.f90"

# - - - - - - - - - -

[[test]]
name = "adapter"
source-dir = "src/structural/adapter"
main = "adapter_main.f90"

[[test]]
name = "proxy"
source-dir = "src/structural/proxy"
main = "proxy_main.f90"