name: mdbook
on: 
  push:
    paths:
    - "doc/src/**.md"
    - "doc/book.toml"
    - "doc/theme/**.js"
    - "src/**.f90"
  
  pull_request:
    braches:
    - main
    paths:
    - "doc/src/**.md"
    - "doc/book.toml"
    - "doc/theme/**.js"
    - "src/**.f90"
    
jobs:
  pages:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook 📔
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.10'
          # mdbook-version: 'latest'

      - run: cd doc && mdbook build
        
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push' && github.repository == 'zoziha/Fortran-Design-Patterns' && ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/book